
package com.example.chernobyl.worldgen.placement;

import com.example.chernobyl.worldgen.feature.CVegetationFeatures;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderGetter;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstapContext;
import net.minecraft.data.worldgen.features.MiscOverworldFeatures;
import net.minecraft.data.worldgen.features.TreeFeatures;
import net.minecraft.data.worldgen.features.VegetationFeatures;
import net.minecraft.data.worldgen.placement.PlacementUtils;
import net.minecraft.data.worldgen.placement.VegetationPlacements;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;
import net.minecraft.world.level.levelgen.placement.*;

import java.util.List;

import static com.example.chernobyl.util.worldgen.CPlacementUtils.createKey;

public class CVegetationPlacements
{
    public static final ResourceKey<PlacedFeature> CLOVER_NORMAL = createKey("patch_clover_normal");
    public static final ResourceKey<PlacedFeature> CLOVER_EXTRA = createKey("patch_clover_extra");
    public static final ResourceKey<PlacedFeature> COLD_DESERT_ROCKS = createKey("cold_desert_rocks");
    public static final ResourceKey<PlacedFeature> HIGHLAND_ROCKS = createKey("highland_rocks");
    public static final ResourceKey<PlacedFeature> HUGE_TOADSTOOL = createKey("huge_toadstool");
    public static final ResourceKey<PlacedFeature> HUGE_CLOVER = createKey("huge_clover");
    public static final ResourceKey<PlacedFeature> HUGE_LILY_PAD = createKey("huge_lily_pad");
    public static final ResourceKey<PlacedFeature> HUGE_RED_MUSHROOM_EXTRA = createKey("huge_red_mushroom_extra");
    public static final ResourceKey<PlacedFeature> PATCH_BARLEY = createKey("patch_barley");
    public static final ResourceKey<PlacedFeature> PATCH_BARLEY_SPARSE = createKey("patch_barley_sparse");
    public static final ResourceKey<PlacedFeature> PATCH_BLUE_HYDRANGEA = createKey("patch_blue_hydrangea");
    public static final ResourceKey<PlacedFeature> PATCH_BUSH_1 = createKey("patch_bush_1");
    public static final ResourceKey<PlacedFeature> PATCH_BUSH_4 = createKey("patch_bush_4");
    public static final ResourceKey<PlacedFeature> PATCH_BUSH_10 = createKey("patch_bush_10");
    public static final ResourceKey<PlacedFeature> PATCH_CATTAIL_NORMAL = createKey("patch_cattail_normal");
    public static final ResourceKey<PlacedFeature> PATCH_CATTAIL_EXTRA = createKey("patch_cattail_extra");
    public static final ResourceKey<PlacedFeature> PATCH_DEAD_GRASS = createKey("patch_dead_grass");
    public static final ResourceKey<PlacedFeature> PATCH_DESERT_GRASS = createKey("patch_desert_grass");
    public static final ResourceKey<PlacedFeature> PATCH_DESERT_GRASS_EXTRA = createKey("patch_desert_grass_extra");
    public static final ResourceKey<PlacedFeature> PATCH_DUNE_GRASS = createKey("patch_dune_grass");
    public static final ResourceKey<PlacedFeature> PATCH_FERN_2 = createKey("patch_fern_2");
    public static final ResourceKey<PlacedFeature> PATCH_FERN_4 = createKey("patch_fern_4");
    public static final ResourceKey<PlacedFeature> PATCH_FERN_8 = createKey("patch_fern_8");
    public static final ResourceKey<PlacedFeature> PATCH_FERN_16 = createKey("patch_fern_16");
    public static final ResourceKey<PlacedFeature> PATCH_GRASS_1 = createKey("patch_grass_1");
    public static final ResourceKey<PlacedFeature> PATCH_GRASS_3 = createKey("patch_grass_3");
    public static final ResourceKey<PlacedFeature> PATCH_GRASS_6 = createKey("patch_grass_6");
    public static final ResourceKey<PlacedFeature> PATCH_GRASS_12 = createKey("patch_grass_12");
    public static final ResourceKey<PlacedFeature> PATCH_GRASS_24 = createKey("patch_grass_24");
    public static final ResourceKey<PlacedFeature> PATCH_ICY_IRIS = createKey("patch_icy_iris");
    public static final ResourceKey<PlacedFeature> PATCH_LARGE_FERN_NORMAL = createKey("patch_large_fern_normal");
    public static final ResourceKey<PlacedFeature> PATCH_LARGE_FERN_EXTRA = createKey("patch_large_fern_extra");
    public static final ResourceKey<PlacedFeature> PATCH_SEA_OATS = createKey("patch_sea_oats");
    public static final ResourceKey<PlacedFeature> PATCH_SPROUTS_1 = createKey("patch_sprouts_1");
    public static final ResourceKey<PlacedFeature> PATCH_SPROUTS_5 = createKey("patch_sprouts_5");
    public static final ResourceKey<PlacedFeature> PATCH_SPROUTS_10 = createKey("patch_sprouts_10");
    public static final ResourceKey<PlacedFeature> PATCH_SPROUTS_15 = createKey("patch_sprouts_15");
    public static final ResourceKey<PlacedFeature> PATCH_TALL_GRASS_6 = createKey("patch_tall_grass_6");
    public static final ResourceKey<PlacedFeature> PATCH_TALL_GRASS_12 = createKey("patch_tall_grass_12");
    public static final ResourceKey<PlacedFeature> PATCH_TALL_GRASS_24 = createKey("patch_tall_grass_24");
    public static final ResourceKey<PlacedFeature> PATCH_TALL_GRASS_64 = createKey("patch_tall_grass_64");
    public static final ResourceKey<PlacedFeature> PATCH_TALL_GRASS_250 = createKey("patch_tall_grass_250");
    public static final ResourceKey<PlacedFeature> PATCH_TALL_LAVENDER = createKey("patch_tall_lavender");
    public static final ResourceKey<PlacedFeature> PATCH_TALL_LAVENDER_FOREST = createKey("patch_tall_lavender_forest");
    public static final ResourceKey<PlacedFeature> PATCH_TUNDRA_SHRUBS = createKey("patch_tundra_shrubs");
    public static final ResourceKey<PlacedFeature> RAINFOREST_CLIFFS_VINES = createKey("rainforest_cliffs_vines");
    public static final ResourceKey<PlacedFeature> SMALL_BROWN_MUSHROOM = createKey("small_brown_mushroom");
    public static final ResourceKey<PlacedFeature> SMALL_TOADSTOOL = createKey("small_toadstool");
    public static final ResourceKey<PlacedFeature> SMALL_RED_MUSHROOM = createKey("small_red_mushroom");
    public static final ResourceKey<PlacedFeature> WASTELAND_GRASS_1 = createKey("wasteland_grass_1");
    public static final ResourceKey<PlacedFeature> WASTELAND_GRASS_2 = createKey("wasteland_grass_2");
    public static final ResourceKey<PlacedFeature> DRIPSTONE_SPLATTER = createKey("dripstone_splatter");
    public static final ResourceKey<PlacedFeature> MYCELIUM_SPLATTER = createKey("mycelium_splatter");
    public static final ResourceKey<PlacedFeature> TOADSTOOL_NORMAL = createKey("toadstool_normal");
    public static final ResourceKey<PlacedFeature> TOADSTOOL_EXTRA = createKey("toadstool_extra");
    public static final ResourceKey<PlacedFeature> LILY_PAD_5 = createKey("patch_lily_pad_5");
    public static final ResourceKey<PlacedFeature> LILY_PAD_10 = createKey("patch_lily_pad_10");
    public static final ResourceKey<PlacedFeature> LILY_PAD_15 = createKey("patch_lily_pad_15");
    public static final ResourceKey<PlacedFeature> WATERLILY_FLOWERS = createKey("patch_waterlily_flowers");
    public static final ResourceKey<PlacedFeature> PATCH_REED_5 = createKey("patch_reed_5");
    public static final ResourceKey<PlacedFeature> PATCH_REED_10 = createKey("patch_reed_10");
    public static final ResourceKey<PlacedFeature> PATCH_WATERGRASS_10 = createKey("patch_watergrass_10");
    public static final ResourceKey<PlacedFeature> PATCH_WATERGRASS_50 = createKey("patch_watergrass_50");
    public static final ResourceKey<PlacedFeature> PATCH_WATERGRASS_250 = createKey("patch_watergrass_250");
    public static final ResourceKey<PlacedFeature> FLOWER_LAVENDER = createKey("flower_lavender");
    public static final ResourceKey<PlacedFeature> FLOWER_LAVENDER_FOREST = createKey("flower_lavender_forest");
    public static final ResourceKey<PlacedFeature> FLOWER_LUSH_DESERT = createKey("flower_lush_desert");
    public static final ResourceKey<PlacedFeature> FLOWER_CLOVER_PATCH = createKey("flower_clover_patch");
    public static final ResourceKey<PlacedFeature> FLOWER_CONIFEROUS_FOREST = createKey("flower_coniferous_forest");
    public static final ResourceKey<PlacedFeature> FLOWER_DEFAULT_EXTENDED_6 = createKey("flower_default_extended_6");
    public static final ResourceKey<PlacedFeature> FLOWER_DEFAULT_EXTENDED_15 = createKey("flower_default_extended_15");
    public static final ResourceKey<PlacedFeature> FLOWER_FIELD_1 = createKey("flower_field_1");
    public static final ResourceKey<PlacedFeature> FLOWER_FIELD_2 = createKey("flower_field_2");
    public static final ResourceKey<PlacedFeature> FLOWER_GRASSLAND = createKey("flower_grassland");
    public static final ResourceKey<PlacedFeature> FLOWER_MOOR = createKey("flower_moor");
    public static final ResourceKey<PlacedFeature> FLOWER_MYSTIC_GROVE = createKey("flower_mystic_grove");
    public static final ResourceKey<PlacedFeature> FLOWER_OMINOUS_WOODS = createKey("flower_ominous_woods");
    public static final ResourceKey<PlacedFeature> FLOWER_ORIGIN_VALLEY = createKey("flower_origin_valley");
    public static final ResourceKey<PlacedFeature> FLOWER_POPPY = createKey("flower_poppy");
    public static final ResourceKey<PlacedFeature> FLOWER_RAINFOREST = createKey("flower_rainforest");
    public static final ResourceKey<PlacedFeature> FLOWER_SCRUBLAND = createKey("flower_scrubland");
    public static final ResourceKey<PlacedFeature> FLOWER_SHRUBLAND = createKey("flower_shrubland");
    public static final ResourceKey<PlacedFeature> FLOWER_SNOWBLOSSOM_GROVE = createKey("flower_snowblossom_grove");
    public static final ResourceKey<PlacedFeature> FLOWER_SNOWY = createKey("flower_snowy");
    public static final ResourceKey<PlacedFeature> FLOWER_TROPICS = createKey("flower_tropics");
    public static final ResourceKey<PlacedFeature> FLOWER_VIOLET = createKey("flower_violet");
    public static final ResourceKey<PlacedFeature> FLOWER_WASTELAND = createKey("flower_wasteland");
    public static final ResourceKey<PlacedFeature> FLOWER_WETLAND = createKey("flower_wetland");
    public static final ResourceKey<PlacedFeature> GOLDENROD = createKey("goldenrod");
    public static final ResourceKey<PlacedFeature> LILAC_NORMAL = createKey("patch_lilac_normal");
    public static final ResourceKey<PlacedFeature> LILAC_EXTRA = createKey("patch_lilac_extra");
    public static final ResourceKey<PlacedFeature> PEONY = createKey("patch_peony");
    public static final ResourceKey<PlacedFeature> ROSE_BUSH_NORMAL = createKey("rose_bush_normal");
    public static final ResourceKey<PlacedFeature> ROSE_BUSH_EXTRA = createKey("rose_bush_extra");
    public static final ResourceKey<PlacedFeature> SUNFLOWER = createKey("sunflower");
    public static final ResourceKey<PlacedFeature> TREES_AURORAL_GARDEN = createKey("trees_auroral_garden");
    public static final ResourceKey<PlacedFeature> TREES_BAYOU = createKey("trees_bayou");
    public static final ResourceKey<PlacedFeature> TREES_BOG = createKey("trees_bog");
    public static final ResourceKey<PlacedFeature> TREES_CONIFEROUS_FOREST = createKey("trees_coniferous_forest");
    public static final ResourceKey<PlacedFeature> TREES_DEAD_FOREST = createKey("trees_dead_forest");
    public static final ResourceKey<PlacedFeature> TREES_DENSE_WOODLAND = createKey("trees_dense_woodland");
    public static final ResourceKey<PlacedFeature> TREES_DRYLAND = createKey("trees_dryland");
    public static final ResourceKey<PlacedFeature> TREES_FIELD = createKey("trees_field");
    public static final ResourceKey<PlacedFeature> TREES_FIELD_FOREST = createKey("trees_field_forest");
    public static final ResourceKey<PlacedFeature> TREES_FUNGAL_JUNGLE = createKey("trees_fungal_jungle");
    public static final ResourceKey<PlacedFeature> TREES_FIR_CLEARING = createKey("trees_fir_clearing");
    public static final ResourceKey<PlacedFeature> TREES_JADE_CLIFFS = createKey("trees_jade_cliffs");
    public static final ResourceKey<PlacedFeature> TREES_LAVENDER_FIELD = createKey("trees_lavender_field");
    public static final ResourceKey<PlacedFeature> TREES_LAVENDER_FOREST = createKey("trees_lavender_forest");
    public static final ResourceKey<PlacedFeature> TREES_LUSH_DESERT = createKey("trees_lush_desert");
    public static final ResourceKey<PlacedFeature> TREES_MAPLE_FOREST = createKey("trees_maple_forest");
    public static final ResourceKey<PlacedFeature> TREES_MEDITERRANEAN_FOREST = createKey("trees_mediterranean_forest");
    public static final ResourceKey<PlacedFeature> TREES_MUSKEG = createKey("trees_muskeg");
    public static final ResourceKey<PlacedFeature> TREES_OLD_GROWTH_DEAD_FOREST = createKey("trees_old_growth_dead_forest");
    public static final ResourceKey<PlacedFeature> TREES_MYSTIC_GROVE = createKey("trees_mystic_grove");
    public static final ResourceKey<PlacedFeature> TREES_OMINOUS_WOODS = createKey("trees_ominous_woods");
    public static final ResourceKey<PlacedFeature> TREES_ORCHARD = createKey("trees_orchard");
    public static final ResourceKey<PlacedFeature> TREES_ORIGIN_VALLEY = createKey("trees_origin_valley");
    public static final ResourceKey<PlacedFeature> TREES_PRAIRIE = createKey("trees_prairie");
    public static final ResourceKey<PlacedFeature> TREES_SCRUBLAND = createKey("trees_scrubland");
    public static final ResourceKey<PlacedFeature> TREES_WASTELAND = createKey("trees_wasteland");
    public static final ResourceKey<PlacedFeature> TREES_WETLAND = createKey("trees_wetland");
    public static final ResourceKey<PlacedFeature> TREES_WOODLAND = createKey("trees_woodland");
    public static final ResourceKey<PlacedFeature> TREES_RAINFOREST = createKey("trees_rainforest");
    public static final ResourceKey<PlacedFeature> TREES_RAINFOREST_CLIFFS = createKey("trees_rainforest_cliffs");
    public static final ResourceKey<PlacedFeature> TREES_RAINFOREST_FLOODPLAIN = createKey("trees_rainforest_floodplain");
    public static final ResourceKey<PlacedFeature> TREES_REDWOOD_FOREST = createKey("trees_redwood_forest");
    public static final ResourceKey<PlacedFeature> TREES_ROCKY_SHRUBLAND = createKey("trees_rocky_shrubland");
    public static final ResourceKey<PlacedFeature> TREES_SHRUBLAND = createKey("trees_shrubland");
    public static final ResourceKey<PlacedFeature> TREES_SEASONAL_FOREST = createKey("trees_seasonal_forest");
    public static final ResourceKey<PlacedFeature> TREES_SEASONAL_ORCHARD = createKey("trees_seasonal_orchard");
    public static final ResourceKey<PlacedFeature> TREES_SEASONAL_PUMPKIN_PATCH = createKey("trees_seasonal_pumpkin_patch");
    public static final ResourceKey<PlacedFeature> TREES_SNOWBLOSSOM_GROVE = createKey("trees_snowblossom_grove");
    public static final ResourceKey<PlacedFeature> TREES_SNOWY_CONIFEROUS_FOREST = createKey("trees_snowy_coniferous_forest");
    public static final ResourceKey<PlacedFeature> TREES_SNOWY_MAPLE_FOREST = createKey("trees_snowy_maple_forest");
    public static final ResourceKey<PlacedFeature> TREES_TROPICS = createKey("trees_tropics");
    public static final ResourceKey<PlacedFeature> TREES_TUNDRA = createKey("trees_tundra");
    public static final ResourceKey<PlacedFeature> TREES_VOLCANIC_PLAINS = createKey("trees_volcanic_plains");
    public static final ResourceKey<PlacedFeature> HIGH_GRASS = createKey("high_grass");
    public static final ResourceKey<PlacedFeature> BIG_DRIPLEAF = createKey("big_dripleaf");
    public static final ResourceKey<PlacedFeature> BIG_PUMPKIN = createKey("big_pumpkin");
    public static final ResourceKey<PlacedFeature> BRAMBLE = createKey("bramble");
    public static final ResourceKey<PlacedFeature> MOSS_SPLATTER = createKey("moss_splatter");
    public static final ResourceKey<PlacedFeature> PUMPKIN_PATCH = createKey("pumpkin_patch");
    public static final ResourceKey<PlacedFeature> ROOTED_STUMP = createKey("rooted_stump");
    public static final ResourceKey<PlacedFeature> SCATTERED_ROCKS = createKey("scattered_rocks");
    public static final ResourceKey<PlacedFeature> SCATTERED_ROCKS_HIGHLAND = createKey("scattered_rocks_highland");
    public static final ResourceKey<PlacedFeature> SCRUB_EXTRA = createKey("scrub_extra");
    public static final ResourceKey<PlacedFeature> SCRUB_NORMAL = createKey("scrub_normal");
    public static final ResourceKey<PlacedFeature> SHORT_BAMBOO = createKey("short_bamboo");
    public static final ResourceKey<PlacedFeature> SMALL_DRIPLEAF = createKey("small_dripleaf");
    public static final ResourceKey<PlacedFeature> FALLEN_LOG = createKey("fallen_log");
    public static final ResourceKey<PlacedFeature> FALLEN_FIR_LOG = createKey("fallen_fir_log");

    public static void bootstrap(BootstapContext<PlacedFeature> context)
    {
        HolderGetter<ConfiguredFeature<?, ?>> configuredFeatureGetter = context.lookup(Registries.CONFIGURED_FEATURE);

        final Holder<ConfiguredFeature<?, ?>> PATCH_CLOVER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_CLOVER);
        final Holder<ConfiguredFeature<?, ?>> HUGE_TOADSTOOL = configuredFeatureGetter.getOrThrow(CVegetationFeatures.HUGE_TOADSTOOL);
        final Holder<ConfiguredFeature<?, ?>> HUGE_CLOVER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.HUGE_CLOVER);
        final Holder<ConfiguredFeature<?, ?>> HUGE_LILY_PAD = configuredFeatureGetter.getOrThrow(CVegetationFeatures.HUGE_LILY_PAD);
        final Holder<ConfiguredFeature<?, ?>> PATCH_BARLEY = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_BARLEY);
        final Holder<ConfiguredFeature<?, ?>> HUGE_RED_MUSHROOM = configuredFeatureGetter.getOrThrow(TreeFeatures.HUGE_RED_MUSHROOM);
        final Holder<ConfiguredFeature<?, ?>> PATCH_BLUE_HYDRANGEA = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_BLUE_HYDRANGEA);
        final Holder<ConfiguredFeature<?, ?>> PATCH_BUSH = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_BUSH);
        final Holder<ConfiguredFeature<?, ?>> PATCH_CATTAIL = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_CATTAIL);
        final Holder<ConfiguredFeature<?, ?>> PATCH_DEAD_GRASS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_DEAD_GRASS);
        final Holder<ConfiguredFeature<?, ?>> PATCH_DESERT_GRASS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_DESERT_GRASS);
        final Holder<ConfiguredFeature<?, ?>> PATCH_DUNE_GRASS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_DUNE_GRASS);
        final Holder<ConfiguredFeature<?, ?>> PATCH_FERN = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_FERN);
        final Holder<ConfiguredFeature<?, ?>> PATCH_GRASS = configuredFeatureGetter.getOrThrow(VegetationFeatures.PATCH_GRASS);
        final Holder<ConfiguredFeature<?, ?>> PATCH_ICY_IRIS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_ICY_IRIS);
        final Holder<ConfiguredFeature<?, ?>> PATCH_LARGE_FERN = configuredFeatureGetter.getOrThrow(VegetationFeatures.PATCH_LARGE_FERN);
        final Holder<ConfiguredFeature<?, ?>> PATCH_SEA_OATS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_SEA_OATS);
        final Holder<ConfiguredFeature<?, ?>> PATCH_SPROUTS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_SPROUTS);
        final Holder<ConfiguredFeature<?, ?>> PATCH_TALL_GRASS = configuredFeatureGetter.getOrThrow(VegetationFeatures.PATCH_TALL_GRASS);
        final Holder<ConfiguredFeature<?, ?>> PATCH_TALL_LAVENDER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_TALL_LAVENDER);
        final Holder<ConfiguredFeature<?, ?>> PATCH_TUNDRA_SHRUBS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_TUNDRA_SHRUBS);
        final Holder<ConfiguredFeature<?, ?>> RAINFOREST_CLIFFS_VINES = configuredFeatureGetter.getOrThrow(CVegetationFeatures.RAINFOREST_CLIFFS_VINES);
        final Holder<ConfiguredFeature<?, ?>> SMALL_BROWN_MUSHROOM = configuredFeatureGetter.getOrThrow(CVegetationFeatures.SMALL_BROWN_MUSHROOM);
        final Holder<ConfiguredFeature<?, ?>> SMALL_TOADSTOOL = configuredFeatureGetter.getOrThrow(CVegetationFeatures.SMALL_TOADSTOOL);
        final Holder<ConfiguredFeature<?, ?>> SMALL_RED_MUSHROOM = configuredFeatureGetter.getOrThrow(CVegetationFeatures.SMALL_RED_MUSHROOM);
        final Holder<ConfiguredFeature<?, ?>> WASTELAND_GRASS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.WASTELAND_GRASS);
        final Holder<ConfiguredFeature<?, ?>> DRIPSTONE_SPLATTER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.DRIPSTONE_SPLATTER);
        final Holder<ConfiguredFeature<?, ?>> MYCELIUM_SPLATTER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.MYCELIUM_SPLATTER);
        final Holder<ConfiguredFeature<?, ?>> TOADSTOOL_NORMAL = configuredFeatureGetter.getOrThrow(CVegetationFeatures.TOADSTOOL_NORMAL);
        final Holder<ConfiguredFeature<?, ?>> PATCH_WATERLILY = configuredFeatureGetter.getOrThrow(VegetationFeatures.PATCH_WATERLILY);
        final Holder<ConfiguredFeature<?, ?>> PATCH_REED = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_REED);
        final Holder<ConfiguredFeature<?, ?>> PATCH_WATERGRASS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_WATERGRASS);
        final Holder<ConfiguredFeature<?, ?>> PATCH_WATERLILY_FLOWER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_WATERLILY_FLOWER);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_LAVENDER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_LAVENDER);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_WILDFLOWER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_WILDFLOWER);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_CLOVER_PATCH = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_CLOVER_PATCH);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_CONIFEROUS_FOREST = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_CONIFEROUS_FOREST);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_DEFAULT_EXTENDED = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_DEFAULT_EXTENDED);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_FIELD_1 = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_FIELD_1);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_FIELD_2 = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_FIELD_2);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_GRASSLAND = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_GRASSLAND);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_MOOR = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_MOOR);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_MYSTIC_GROVE = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_MYSTIC_GROVE);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_OMINOUS_WOODS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_OMINOUS_WOODS);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_ORIGIN_VALLEY = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_ORIGIN_VALLEY);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_POPPY = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_POPPY);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_RAINFOREST = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_RAINFOREST);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_SHRUBLAND = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_SHRUBLAND);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_SNOWBLOSSOM_GROVE = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_SNOWBLOSSOM_GROVE);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_SNOWY = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_SNOWY);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_TROPICS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_TROPICS);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_VIOLET = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_VIOLET);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_WASTELAND = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_WASTELAND);
        final Holder<ConfiguredFeature<?, ?>> FLOWER_WETLAND = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FLOWER_WETLAND);
        final Holder<ConfiguredFeature<?, ?>> GOLDENROD = configuredFeatureGetter.getOrThrow(CVegetationFeatures.GOLDENROD);
        final Holder<ConfiguredFeature<?, ?>> PATCH_LILAC = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_LILAC);
        final Holder<ConfiguredFeature<?, ?>> PATCH_PEONY = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PATCH_PEONY);
        final Holder<ConfiguredFeature<?, ?>> ROSE_BUSH = configuredFeatureGetter.getOrThrow(CVegetationFeatures.ROSE_BUSH);
        final Holder<ConfiguredFeature<?, ?>> SUNFLOWER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.SUNFLOWER);
        final Holder<ConfiguredFeature<?, ?>> HIGH_GRASS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.HIGH_GRASS);
        final Holder<ConfiguredFeature<?, ?>> BIG_DRIPLEAF = configuredFeatureGetter.getOrThrow(CVegetationFeatures.BIG_DRIPLEAF);
        final Holder<ConfiguredFeature<?, ?>> BIG_PUMPKIN = configuredFeatureGetter.getOrThrow(CVegetationFeatures.BIG_PUMPKIN);
        final Holder<ConfiguredFeature<?, ?>> BRAMBLE = configuredFeatureGetter.getOrThrow(CVegetationFeatures.BRAMBLE);
        final Holder<ConfiguredFeature<?, ?>> MOSS_SPLATTER = configuredFeatureGetter.getOrThrow(CVegetationFeatures.MOSS_SPLATTER);
        final Holder<ConfiguredFeature<?, ?>> PUMPKIN_PATCH = configuredFeatureGetter.getOrThrow(CVegetationFeatures.PUMPKIN_PATCH);
        final Holder<ConfiguredFeature<?, ?>> ROOTED_STUMP = configuredFeatureGetter.getOrThrow(CVegetationFeatures.ROOTED_STUMP);
        final Holder<ConfiguredFeature<?, ?>> SCATTERED_ROCKS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.SCATTERED_ROCKS);
        final Holder<ConfiguredFeature<?, ?>> SCRUB = configuredFeatureGetter.getOrThrow(CVegetationFeatures.SCRUB);
        final Holder<ConfiguredFeature<?, ?>> SHORT_BAMBOO = configuredFeatureGetter.getOrThrow(CVegetationFeatures.SHORT_BAMBOO);
        final Holder<ConfiguredFeature<?, ?>> SMALL_DRIPLEAF = configuredFeatureGetter.getOrThrow(CVegetationFeatures.SMALL_DRIPLEAF);
        final Holder<ConfiguredFeature<?, ?>> FALLEN_LOG = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FALLEN_LOG);
        final Holder<ConfiguredFeature<?, ?>> FALLEN_FIR_LOG = configuredFeatureGetter.getOrThrow(CVegetationFeatures.FALLEN_FIR_LOG);
        final Holder<ConfiguredFeature<?, ?>> HIGHLAND_ROCKS = configuredFeatureGetter.getOrThrow(MiscOverworldFeatures.FOREST_ROCK);
        final Holder<ConfiguredFeature<?, ?>> COLD_DESERT_ROCKS = configuredFeatureGetter.getOrThrow(CVegetationFeatures.COLD_DESERT_ROCKS);

        register(context, CVegetationPlacements.CLOVER_NORMAL, PATCH_CLOVER, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.CLOVER_EXTRA, PATCH_CLOVER, VegetationPlacements.worldSurfaceSquaredWithCount(7));
        register(context, CVegetationPlacements.COLD_DESERT_ROCKS, COLD_DESERT_ROCKS, RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.HIGHLAND_ROCKS, HIGHLAND_ROCKS, RarityFilter.onAverageOnceEvery(3), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.HUGE_TOADSTOOL, HUGE_TOADSTOOL, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.HUGE_CLOVER, HUGE_CLOVER, VegetationPlacements.worldSurfaceSquaredWithCount(6));
        register(context, CVegetationPlacements.HUGE_LILY_PAD, HUGE_LILY_PAD, VegetationPlacements.worldSurfaceSquaredWithCount(10));
        register(context, CVegetationPlacements.HUGE_RED_MUSHROOM_EXTRA, HUGE_RED_MUSHROOM, RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.PATCH_BARLEY, PATCH_BARLEY, VegetationPlacements.worldSurfaceSquaredWithCount(10));
        register(context, CVegetationPlacements.PATCH_BARLEY_SPARSE, PATCH_BARLEY, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PATCH_BLUE_HYDRANGEA, PATCH_BLUE_HYDRANGEA, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PATCH_BUSH_1, PATCH_BUSH, VegetationPlacements.worldSurfaceSquaredWithCount(1));
        register(context, CVegetationPlacements.PATCH_BUSH_4, PATCH_BUSH, VegetationPlacements.worldSurfaceSquaredWithCount(3));
        register(context, CVegetationPlacements.PATCH_BUSH_10, PATCH_BUSH, VegetationPlacements.worldSurfaceSquaredWithCount(8));
        register(context, CVegetationPlacements.PATCH_CATTAIL_NORMAL, PATCH_CATTAIL, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.PATCH_CATTAIL_EXTRA, PATCH_CATTAIL, VegetationPlacements.worldSurfaceSquaredWithCount(5));
        register(context, CVegetationPlacements.PATCH_DEAD_GRASS, PATCH_DEAD_GRASS, List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PATCH_DESERT_GRASS, PATCH_DESERT_GRASS, VegetationPlacements.worldSurfaceSquaredWithCount(1));
        register(context, CVegetationPlacements.PATCH_DESERT_GRASS_EXTRA, PATCH_DESERT_GRASS, VegetationPlacements.worldSurfaceSquaredWithCount(3));
        register(context, CVegetationPlacements.PATCH_DUNE_GRASS, PATCH_DUNE_GRASS, VegetationPlacements.worldSurfaceSquaredWithCount(4));
        register(context, CVegetationPlacements.PATCH_FERN_2, PATCH_FERN, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.PATCH_FERN_4, PATCH_FERN, VegetationPlacements.worldSurfaceSquaredWithCount(4));
        register(context, CVegetationPlacements.PATCH_FERN_8, PATCH_FERN, VegetationPlacements.worldSurfaceSquaredWithCount(8));
        register(context, CVegetationPlacements.PATCH_FERN_16, PATCH_FERN, VegetationPlacements.worldSurfaceSquaredWithCount(16));
        register(context, CVegetationPlacements.PATCH_GRASS_1, PATCH_GRASS, VegetationPlacements.worldSurfaceSquaredWithCount(1));
        register(context, CVegetationPlacements.PATCH_GRASS_3, PATCH_GRASS, VegetationPlacements.worldSurfaceSquaredWithCount(3));
        register(context, CVegetationPlacements.PATCH_GRASS_6, PATCH_GRASS, VegetationPlacements.worldSurfaceSquaredWithCount(6));
        register(context, CVegetationPlacements.PATCH_GRASS_12, PATCH_GRASS, VegetationPlacements.worldSurfaceSquaredWithCount(12));
        register(context, CVegetationPlacements.PATCH_GRASS_24, PATCH_GRASS, VegetationPlacements.worldSurfaceSquaredWithCount(24));
        register(context, CVegetationPlacements.PATCH_ICY_IRIS, PATCH_ICY_IRIS, List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PATCH_LARGE_FERN_NORMAL, PATCH_LARGE_FERN, RarityFilter.onAverageOnceEvery(7), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.PATCH_LARGE_FERN_EXTRA, PATCH_LARGE_FERN, RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.PATCH_SEA_OATS, PATCH_SEA_OATS, VegetationPlacements.worldSurfaceSquaredWithCount(5));
        register(context, CVegetationPlacements.PATCH_SPROUTS_1, PATCH_SPROUTS, RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.PATCH_SPROUTS_5, PATCH_SPROUTS, VegetationPlacements.worldSurfaceSquaredWithCount(1));
        register(context, CVegetationPlacements.PATCH_SPROUTS_10, PATCH_SPROUTS, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.PATCH_SPROUTS_15, PATCH_SPROUTS, VegetationPlacements.worldSurfaceSquaredWithCount(6));
        register(context, CVegetationPlacements.PATCH_TALL_GRASS_6, PATCH_TALL_GRASS, RarityFilter.onAverageOnceEvery(8), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.PATCH_TALL_GRASS_12, PATCH_TALL_GRASS, RarityFilter.onAverageOnceEvery(6), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.PATCH_TALL_GRASS_24, PATCH_TALL_GRASS, RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.PATCH_TALL_GRASS_64, PATCH_TALL_GRASS, RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.PATCH_TALL_GRASS_250, PATCH_TALL_GRASS, RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.PATCH_TALL_LAVENDER, PATCH_TALL_LAVENDER, List.of(RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PATCH_TALL_LAVENDER_FOREST, PATCH_TALL_LAVENDER, List.of(RarityFilter.onAverageOnceEvery(3), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PATCH_TUNDRA_SHRUBS, PATCH_TUNDRA_SHRUBS, VegetationPlacements.worldSurfaceSquaredWithCount(3));
        register(context, CVegetationPlacements.RAINFOREST_CLIFFS_VINES, RAINFOREST_CLIFFS_VINES, VegetationPlacements.worldSurfaceSquaredWithCount(10));
        register(context, CVegetationPlacements.SMALL_BROWN_MUSHROOM, SMALL_BROWN_MUSHROOM, List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.SMALL_TOADSTOOL, SMALL_TOADSTOOL, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.SMALL_RED_MUSHROOM, SMALL_RED_MUSHROOM, List.of(RarityFilter.onAverageOnceEvery(6), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.WASTELAND_GRASS_1, WASTELAND_GRASS, List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.WASTELAND_GRASS_2, WASTELAND_GRASS, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.DRIPSTONE_SPLATTER, DRIPSTONE_SPLATTER, List.of(RarityFilter.onAverageOnceEvery(3), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.MYCELIUM_SPLATTER, MYCELIUM_SPLATTER, List.of(RarityFilter.onAverageOnceEvery(3), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.TOADSTOOL_NORMAL, TOADSTOOL_NORMAL, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.TOADSTOOL_EXTRA, TOADSTOOL_NORMAL, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.LILY_PAD_5, PATCH_WATERLILY, RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.LILY_PAD_10, PATCH_WATERLILY, RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.LILY_PAD_15, PATCH_WATERLILY, VegetationPlacements.worldSurfaceSquaredWithCount(15));
        register(context, CVegetationPlacements.WATERLILY_FLOWERS, PATCH_WATERLILY_FLOWER, VegetationPlacements.worldSurfaceSquaredWithCount(3));
        register(context, CVegetationPlacements.PATCH_REED_5, PATCH_REED, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_TOP_SOLID, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PATCH_REED_10, PATCH_REED, List.of(RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_TOP_SOLID, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PATCH_WATERGRASS_10, PATCH_WATERGRASS, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_TOP_SOLID, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PATCH_WATERGRASS_50, PATCH_WATERGRASS, seagrassPlacement(10));
        register(context, CVegetationPlacements.PATCH_WATERGRASS_250, PATCH_WATERGRASS, seagrassPlacement(100));
        register(context, CVegetationPlacements.FLOWER_LAVENDER, FLOWER_LAVENDER, VegetationPlacements.worldSurfaceSquaredWithCount(15));
        register(context, CVegetationPlacements.FLOWER_LAVENDER_FOREST, FLOWER_LAVENDER, VegetationPlacements.worldSurfaceSquaredWithCount(1));
        register(context, CVegetationPlacements.FLOWER_LUSH_DESERT, FLOWER_WILDFLOWER, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_CLOVER_PATCH, FLOWER_CLOVER_PATCH, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_CONIFEROUS_FOREST, FLOWER_CONIFEROUS_FOREST, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_DEFAULT_EXTENDED_6, FLOWER_DEFAULT_EXTENDED, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_DEFAULT_EXTENDED_15, FLOWER_DEFAULT_EXTENDED, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_FIELD_1, FLOWER_FIELD_1, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_FIELD_2, FLOWER_FIELD_2, List.of(RarityFilter.onAverageOnceEvery(8), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_GRASSLAND, FLOWER_GRASSLAND, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_MOOR, FLOWER_MOOR, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_MYSTIC_GROVE, FLOWER_MYSTIC_GROVE, List.of(RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_OMINOUS_WOODS, FLOWER_OMINOUS_WOODS, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_ORIGIN_VALLEY, FLOWER_ORIGIN_VALLEY, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_POPPY, FLOWER_POPPY, VegetationPlacements.worldSurfaceSquaredWithCount(15));
        register(context, CVegetationPlacements.FLOWER_RAINFOREST, FLOWER_RAINFOREST, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_SCRUBLAND, FLOWER_WILDFLOWER, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_SHRUBLAND, FLOWER_SHRUBLAND, List.of(RarityFilter.onAverageOnceEvery(5), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_SNOWBLOSSOM_GROVE, FLOWER_SNOWBLOSSOM_GROVE, NoiseThresholdCountPlacement.of(-0.8D, 5, 10), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome());
        register(context, CVegetationPlacements.FLOWER_SNOWY, FLOWER_SNOWY, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_TROPICS, FLOWER_TROPICS, List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_VIOLET, FLOWER_VIOLET, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.FLOWER_WASTELAND, FLOWER_WASTELAND, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FLOWER_WETLAND, FLOWER_WETLAND, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.GOLDENROD, GOLDENROD, List.of(RarityFilter.onAverageOnceEvery(5), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.LILAC_NORMAL, PATCH_LILAC, List.of(RarityFilter.onAverageOnceEvery(5), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.LILAC_EXTRA, PATCH_LILAC, List.of(RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PEONY, PATCH_PEONY, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.ROSE_BUSH_NORMAL, ROSE_BUSH, List.of(RarityFilter.onAverageOnceEvery(5), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.ROSE_BUSH_EXTRA, ROSE_BUSH, List.of(RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.SUNFLOWER, SUNFLOWER, List.of(RarityFilter.onAverageOnceEvery(5), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.HIGH_GRASS, HIGH_GRASS, VegetationPlacements.worldSurfaceSquaredWithCount(30));
        register(context, CVegetationPlacements.BIG_DRIPLEAF, BIG_DRIPLEAF, List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.BIG_PUMPKIN, BIG_PUMPKIN, List.of(RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.BRAMBLE, BRAMBLE, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.MOSS_SPLATTER, MOSS_SPLATTER, List.of(RarityFilter.onAverageOnceEvery(3), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.PUMPKIN_PATCH, PUMPKIN_PATCH, List.of(RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.ROOTED_STUMP, ROOTED_STUMP, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.SCATTERED_ROCKS, SCATTERED_ROCKS, List.of(RarityFilter.onAverageOnceEvery(5), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.SCATTERED_ROCKS_HIGHLAND, SCATTERED_ROCKS, List.of(RarityFilter.onAverageOnceEvery(7), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.SCRUB_EXTRA, SCRUB, List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.SCRUB_NORMAL, SCRUB, List.of(RarityFilter.onAverageOnceEvery(4), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.SHORT_BAMBOO, SHORT_BAMBOO, VegetationPlacements.worldSurfaceSquaredWithCount(2));
        register(context, CVegetationPlacements.SMALL_DRIPLEAF, SMALL_DRIPLEAF, List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FALLEN_LOG, FALLEN_LOG, List.of(RarityFilter.onAverageOnceEvery(2), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
        register(context, CVegetationPlacements.FALLEN_FIR_LOG, FALLEN_FIR_LOG, List.of(RarityFilter.onAverageOnceEvery(1), InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP, BiomeFilter.biome()));
    }

    private static List<PlacementModifier> seagrassPlacement(int p_195234_) {
        return List.of(InSquarePlacement.spread(), PlacementUtils.HEIGHTMAP_TOP_SOLID, CountPlacement.of(p_195234_), BiomeFilter.biome());
    }

    protected static void register(BootstapContext<PlacedFeature> context, ResourceKey<PlacedFeature> placedFeatureKey, Holder<ConfiguredFeature<?, ?>> configuredFeature, PlacementModifier... modifiers)
    {
        register(context, placedFeatureKey, configuredFeature, List.of(modifiers));
    }

    protected static void register(BootstapContext<PlacedFeature> context, ResourceKey<PlacedFeature> placedFeatureKey, Holder<ConfiguredFeature<?, ?>> configuredFeature, List<PlacementModifier> modifiers)
    {
        context.register(placedFeatureKey, new PlacedFeature(configuredFeature, modifiers));
    }
}
